version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'localhost -> http://web:3000'
      STAGE: "${ENV}"
      CLIENT_MAX_BODY_SIZE: 10M
    volumes:
      - "./certs:/var/lib/https-portal"
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
